language: android

sudo:
  false

android:
  components:
    - platform-tools
    - tools

jdk:
  - oraclejdk8

script:
  - bash build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
