name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Clean and build the project
        run: |
          ./gradlew --no-daemon clean build
      - name: Run UI and integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: pixel_4_xl
          script: ./gradlew --no-daemon :android:connectedCheck
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
      - name: Uploading test coverage reports
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
